---
- name: Install Docker and Docker Compose
  hosts: all
  become: true
  vars:
    docker_compose_path: /usr/local/bin/docker-compose

  tasks:
    - name: Gather OS info
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'min'

    - name: Install dependencies for CentOS
      when: ansible_facts['os_family'] == "RedHat"
      ansible.builtin.yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repo for CentOS
      when: ansible_facts['os_family'] == "RedHat"
      ansible.builtin.command: >
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker for CentOS
      when: ansible_facts['os_family'] == "RedHat"
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Install dependencies for Ubuntu
      when: ansible_facts['os_family'] == "Debian"
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        update_cache: yes
        state: present

    - name: Add Docker GPG key for Ubuntu
      when: ansible_facts['os_family'] == "Debian"
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker repo for Ubuntu
      when: ansible_facts['os_family'] == "Debian"
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable"
        filename: docker
        state: present

    - name: Install Docker for Ubuntu
      when: ansible_facts['os_family'] == "Debian"
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: present

    - name: Enable and start Docker service
      ansible.builtin.service:
        name: docker
        enabled: yes
        state: started

    - name: Add current user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: "{{ docker_compose_path }}"
        mode: '0755'

    - name: Verify Docker version
      ansible.builtin.command: docker --version
      register: docker_version_output

    - name: Show Docker version
      ansible.builtin.debug:
        var: docker_version_output.stdout

    - name: Verify Docker Compose version
      ansible.builtin.command: docker-compose --version
      register: docker_compose_version_output

    - name: Show Docker Compose version
      ansible.builtin.debug:
        var: docker_compose_version_output.stdout
