---
- name: Install Docker and Docker Compose
  hosts: all
  become: true
  tasks:

    - name: Gather OS info
      ansible.builtin.setup:

    - name: Install required packages (Ubuntu)
      when: ansible_facts['os_family'] == "Debian"
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker GPG key (Ubuntu)
      when: ansible_facts['os_family'] == "Debian"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository (Ubuntu)
      when: ansible_facts['os_family'] == "Debian"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable"
        state: present
        filename: docker

    - name: Install Docker (Ubuntu)
      when: ansible_facts['os_family'] == "Debian"
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Install required packages (CentOS)
      when: ansible_facts['os_family'] == "RedHat"
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker YUM repository (CentOS)
      when: ansible_facts['os_family'] == "RedHat"
      yum_repository:
        name: docker-ce
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes

    - name: Install Docker (CentOS)
      when: ansible_facts['os_family'] == "RedHat"
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Add user to docker group
      user:
        name: "{{ ansible_user | default('ubuntu') }}"
        groups: docker
        append: yes

    - name: Check Docker version
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Check Docker Compose version
      command: docker-compose --version
      register: compose_version
      changed_when: false

    - name: Print Docker version
      debug:
        msg: "{{ docker_version.stdout }}"

    - name: Print Docker Compose version
      debug:
        msg: "{{ compose_version.stdout }}"
