---
- name: Install Docker and Docker Compose
  hosts: all
  become: yes
  vars:
    docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
    docker_repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

  tasks:
    - name: Gather OS distribution
      ansible.builtin.setup:
        gather_subset:
          - "distribution"

    - name: Install dependencies for Ubuntu
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Add Docker GPG key for Ubuntu
      ansible.builtin.get_url:
        url: "{{ docker_apt_key_url }}"
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
        mode: '0644'
      when: ansible_distribution == "Ubuntu"

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "{{ docker_repo }}"
        state: present
        filename: docker
      when: ansible_distribution == "Ubuntu"

    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Docker on Ubuntu
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Docker on CentOS
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      when: ansible_distribution == "CentOS"

    - name: Add Docker YUM repository
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
      when: ansible_distribution == "CentOS"

    - name: Install Docker packages on CentOS
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      when: ansible_distribution == "CentOS"

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Install Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker version
      command: docker --version
      register: docker_version_output
      changed_when: false

    - name: Show Docker version
      debug:
        msg: "{{ docker_version_output.stdout }}"

    - name: Verify Docker Compose version
      command: docker-compose --version
      register: compose_version_output
      changed_when: false

    - name: Show Docker Compose version
      debug:
        msg: "{{ compose_version_output.stdout }}"
